name: "Ultracode Self-Check"

on:
  push:
    branches: [ "master", "main" ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check JSON and Markdown
        run: |
          echo "Здесь GitHub проверяет код плагина на ошибки каждый раз, когда мы делаем git push"
          echo "Всё работает!"
